// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "5db5188a-5e20-4df3-9a40-266644f15aa9");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1537884447);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1537884567);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1537884087);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1537884327);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1537884207);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1537884807);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1537884687);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1537884058);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 69);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0af6b051-71b1-4603-a75a-3169f8bddeed}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1537808400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1537884059);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1537884117196");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1537885902196");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1537884074971");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1537887674971");
user_pref("browser.search.countryCode", "ID");
user_pref("browser.search.region", "ID");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1537884060");
user_pref("browser.slowStartup.averageTime", 4652);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180913170256");
user_pref("browser.startup.homepage_override.mstone", "62.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 1);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "62.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "b85fa8cd39dc4e81abac024b71ab846b");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1537884450);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "62.0");
user_pref("extensions.lastPlatformVersion", "62.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"a5fac206-733e-4525-bb46-9a8b52d77615\",\"screenshots@mozilla.org\":\"53e625fa-ef1d-4d85-9da5-5982aefe991a\"}");
user_pref("idle.lastDailyNotification", 1537884853);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1537884340);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180913170256");
user_pref("media.gmp-manager.lastCheck", 1537884327);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1537884854);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "6a14bc2e-87fe-44ae-9685-5e9c3236df54");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1537884854);
user_pref("toolkit.startup.last_success", 1537884054);
user_pref("toolkit.telemetry.cachedClientID", "a2d11807-b20a-45a3-af08-09e323ee1e6a");
user_pref("toolkit.telemetry.previousBuildID", "20180913170256");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
